name: ShuffleDNS Recon

on:
  workflow_dispatch:
    inputs:
      target_domain:
        description: 'Target Domain (e.g., example.com)'
        required: true
        type: string

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MassDNS
      run: |
        git clone https://github.com/blechschmidt/massdns.git
        cd massdns
        make
        sudo cp bin/massdns /usr/local/bin/massdns

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Install ShuffleDNS
      run: |
        go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest

    - name: Setup Dependencies and Wordlists
      run: |
        sudo apt-get update
        sudo apt-get install -y crunch
        mkdir -p wordlists
        cd wordlists
        crunch 1 4 abcdefghijklmnopqrstuvwxyz1234567890 > 4_chars.txt
        wget -q https://github.com/zzzteph/substats/raw/main/wordlists/all -O all.txt
        wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/combined_subdomains.txt -O combined.txt
        wget -q https://memoryleaks.ir/wordlist/10m-sub-voorivex.txt -O yasho.txt
        wget -q https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_huge.txt -O kovo_subs.txt
        wget -q https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt -O best-dns-wordlist.txt
        wget -q https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt -O 2m-subdomains.txt
        wget -q https://wordlists-cdn.assetnote.io/data/automated/httparchive_subdomains_2024_01_28.txt -O all_subs.txt
        cat *.txt | sort -u > ../full.txt
        cd ..
        wget -q https://raw.githubusercontent.com/trickest/resolvers/main/resolvers-trusted.txt -O resolvers.txt

    - name: Execute ShuffleDNS
      run: |
        ~/go/bin/shuffledns -w full.txt -d ${{ inputs.target_domain }} -r resolvers.txt -m /usr/local/bin/massdns -o output.txt -mode bruteforce

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.target_domain }}-subdomains
        path: output.txt
